version: "3.3"
services:
  core-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    command: >
      /bin/sh -c "npx nodemon"
    ports:
      - "4000:4000"
    links:
      - mongodb
    depends_on:
      mongodb:
        condition: service_healthy
  mongodb:
    image: mongo:latest
    expose:
      - 27017
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s

