version: "3.3"
services:
  core-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    command: >
      /bin/sh -c "npx nodemon"
    ports:
      - "4000:4000"
    links:
      - postgres_container_development
    depends_on:
      postgres_container_development:
        condition: service_healthy
  postgres_container_development:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dashboard_be_development_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5        